### PR TITLE
Make solarized colors optional

### PR DESCRIPTION
**Pull request by jhillyerd**
- Add yimmy_solarized variable (default=true)
- Update README.md

### CODE REVIEW

**Comment by derekstavis** [comment]
Are you the original creator of this theme? We can make you an admin again if you are.

**Comment by jhillyerd** [comment]
Yes, I am the Yimmy in question. :)

**Comment by bpinto** [comment]
@jhillyerd Your admin rights have been restored!

**Comment by jhillyerd** [comment]
@bpinto Gracias!

**Pull request merged**
